### ISSUE TITLE
Move required deps from devDependencies to dependencies as Errors when node production mode is used NODE_ENV="production"

### ISSUE THREAD

**Issue by emanuelb** [melis-wallet/melis-cm-client#10]
running `NODE_ENV="production" yarn`
return error:
```
$ cd ./node_modules/emblem && yarn && yarn run build
/bin/sh: 1: cd: can't cd to ./node_modules/emblem
```
as emblem in devDependencies instead of dependencies
https://github.com/melis-wallet/melis-cm-client/blob/830a08142cc51c3f236d95cbd9699c497dfa7109/package.json#L115

Move all deps in devDependencies that are required to compile the android/ios app to dependencies and ensure app compilation works when env var `NODE_ENV="production"` is set.

**Comment by ghost** [comment]
You do not need to set the NODE_ENV environment variable while compiling a production application.

**Comment by emanuelb** [comment]
Using `npm ci` will fail as well cause it's using node production mode as well, dependencies used to build the app should be in `dependencies` and not in `devDependencies` inside `package.json` file.
The node production mode should be used when compiling a release version.

**Comment by ghost** [comment]
That's how ember/ember-cli work, dependencies that are only used for *building* the final application go in `devDependencies`. Feel free to bring the issue to their community if you think it is in error.
