### ISSUE TITLE
Missing code for version 1.6.15 in google-play

### ISSUE THREAD

**Issue by emanuelb** [melis-wallet/melis-cm-client#2]
The version in google-play is: 1.6.15 Updated: March 1, 2021
https://play.google.com/store/apps/details?id=io.melis.clientwallet
While the latest version found in this repo is 1.5.41 from commit:
https://github.com/melis-wallet/melis-cm-client/commit/61246945952eb3c50ef8c7800eba84bea1142836
on: Jan 2, 2020

Please Release/Publish the code for latest 1.6.15 version on google-play.

**Comment by Polve** [comment]
We plan to update the repository with the latest version in the next few days. The process is manual and takes a bit of time, in the long run we plan to rebuild a new version from scratch with real time updates on the source code.

**Comment by emanuelb** [comment]
Any update? when will you publish the source-code for the latest version in google-play? more then 1 month was passed from previous comment.

**Comment by Polve** [comment]
You are right, I'll try to push for the publishing

**Comment by ghost** [comment]
We have published a snapshot of the current 1.6.18 release, which is the release currently deployed as the web application at wallet.melis.io.
The `release-1.6.5` branch contains a snapshot of the version used for the mobile/desktop applications, for reference. It's a couple of minor bugfixes behind and some documentation.
