### ISSUE TITLE
what/where is ChainMaster directory?

### ISSUE THREAD

**Issue by emanuelb** [melis-wallet/melis-cm-client#4]
The build instructions tell to run `node i18n/generate-melis-i18n.js` which return error: 
> ../ChainMaster not found: skipping server messages

https://github.com/melis-wallet/melis-cm-client/blob/71e0bdc72d585a8f8ec0eb0dcdb754901d462c87/i18n/generate-melis-i18n.js#L13

also the `./build/build-android.sh` file use this directory as location for keystore at `ChainMaster/etc/melis-android.keystore`.

https://github.com/melis-wallet/melis-cm-client/blob/71e0bdc72d585a8f8ec0eb0dcdb754901d462c87/build/build-android.sh#L37-L39

can you provide more details about this directory and what files should be there (or are located there)

**Comment by ghost** [comment]
Refer to the 1.6.18 README for instructions on how to build the wallet. 
The 1.6.15 is only provided as reference, we can't correct the README retroactively, can we?

**Comment by ghost** [comment]
I would suggest to try building the *web* version for 1.6.18 following the instructions in the README.
There is a single file `app/controllers/main/account/view.coffee` differing between 1.6.15 and 1.6.18, check in the diffs.
Start with the "web" version, meanwhile we'll review the android build process outside of our build pipeline.
