### ISSUE TITLE
Add .apk & .ipa files to github releases

### ISSUE THREAD

**Issue by emanuelb** [melis-wallet/melis-cm-client#8]
Add .ipa file (ios app) & universal .apk (android app) to the releases as assets at github releases:
https://github.com/melis-wallet/melis-cm-client/releases

**Comment by emanuelb** [comment]
Only .apk files was uploaded to 1.6.21 release, .ipa file (iOS app) should be uploaded as well
https://github.com/melis-wallet/melis-cm-client/releases/tag/1.6.21

**Comment by Polve** [comment]
Does Apple allow to install / run an .ipa file on their device?

**Comment by emanuelb** [comment]
Don't know about side-loading story on apple devices, it might be possible?! also there is virtualization of iOS by corellium which might be used to install the .ipa file as well:
https://github.com/corellium/corellium-api#async-installpath-progress

Other purposes and usage of published .ipa besides installing it on device/virtualization are:

1. Reproducible builds, see this comment and issue for more details to understand why publishing the .ipa is needed: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/149#note_537109159
2. looking at the file content after unzip, might report issues if found some during so
3. comparing the content of .ipa between versions with diffoscope https://diffoscope.org/

And there probably other usages as well..
