### ISSUE TITLE
Insecure /tmp usage with static path /tmp/a (use mktemp instead or not shared /tmp)

### ISSUE THREAD

**Issue by emanuelb** [melis-wallet/melis-cm-client#9]
Static folder path `/tmp/a` is used in: 
https://github.com/melis-wallet/melis-cm-client/blob/71e0bdc72d585a8f8ec0eb0dcdb754901d462c87/build/build-android.sh#L21

thus vulnerable to malicious usage from other users/processes which will create it the dir in advance with link to another location (or the files written to it as a link, etc...)

Using mktemp to generate the tmp file is better, also creating a temporary directory with `mktemp -d` and working with static names in it is ok (or creating temp dir for each usage by `mktemp -d --suffix='-some-related-suffix'`), also not using shared `/tmp/` but another location like `/home/user/tmp/` or `~/tmp/` is also a fix.

**Comment by ghost** [comment]
```
 The following steps are provided only as a reference for building the Cordova Android/iOS application. You're on your own here. We understand this part is not user-friendly, we're working on it.
```

You are welcome to provide a PR with a more user friendly script to build the android/ios/cordova version. As long as it stays compatible with ours (ie: picks the keyring and puts the artifacts in the right places, at least with a switch) I'd be more than happy to merge it.

**Comment by emanuelb** [comment]
My latest try to compile the app failed, see Containerfile which is script to compile latest version in container at comment:
https://github.com/melis-wallet/melis-cm-client/issues/5#issuecomment-840028727

Regarding this issue using static names in /tmp/ shared folder it's wrong for several reasons including security, you can read more about it:
https://stackoverflow.com/questions/11636790/why-do-we-need-mktemp
